module.exports = [
  { q: "How many weddings have you coordinated?", a: "I have coordinated over 230 weddings, each unique and special. My experience allows me to handle various scenarios with confidence and creativity." },
  { q: "What is your pricing structure?", a: "I offer transparent pricing with different packages to fit various budgets. My pricing is right here on my website, or you can call me directly at (503) 502-9231, and we'll discuss what works best for you during an initial consultation." },
  { q: "Do you have experience with our specific venue?", a: "I've worked at various venues in and around Oregon and Washington — more than likely I've worked at yours before and understand its layout and logistics. That experience lets me navigate the space effectively and maximize its potential." },
  { q: "How do you handle vendor recommendations?", a: "I have a trusted network of professional vendors I've worked with, but I'll also consider your preferences. Together we'll find the best fits for your vision and budget." },
  { q: "What is your communication style and frequency?", a: "I believe in open communication and will keep you updated regularly via email or phone, based on your preference. I use a 3-month, 2-month, and 1-month checklist to keep us on the same page leading up to your day — and you can reach out anytime with questions along the way." },
  { q: "Will you be present during the entire wedding day?", a: "Yes — I'll be there from start to finish, overseeing every detail so you can relax and focus on enjoying your special day." },
  { q: "How do you handle last-minute changes or emergencies?", a: "I thrive in high-pressure situations and always have contingency plans in place. I'll address any issues discreetly and efficiently, so you can simply enjoy your day." },
  { q: "What happens if the weather affects our outdoor plans?", a: "Being in the Pacific Northwest, I always recommend a contingency plan — tents, canopies, or moving indoors if needed. We'll discuss options ahead of time so you feel prepared no matter what." },
  { q: "Are you insured and bonded?", a: "Yes. Insurance protects against unforeseen events, and being bonded adds a layer of security and trust. Together these demonstrate professionalism and commitment — and I always recommend working with vendors who are insured and bonded too." },
  { q: "Do you charge for travel?", a: "For any location more than 45 miles outside of Oregon City, a $350 travel and accommodation fee applies. This applies to the day of the wedding only." },
  { q: "What if I change my mind?", a: "Plans can change, and I handle date changes or postponements with care. For changes made more than 90 days before the wedding date, there are no additional rescheduling fees and your non-refundable retainer applies to the new date. One date change is permitted without additional fees." },
  { q: "How do I pay?", a: "Payment can be made via Square, Venmo, Zelle, and check or cash. Please note there is a 3% service fee for Square." },
];
