// Package inclusions and long-form descriptions recovered from the previous
// WordPress site (/wedding-packages/ and /services/). Prices below are the
// CURRENT prices — the archived pages listed older, lower figures.
module.exports = {
  // "What to expect" trio, also recovered from the old /services/ page.
  expect: [
    {
      title: "Communication",
      tagline: "Clear | Decisive | Detailed",
      text: "From our initial consultation to the final moments of your wedding night, I take great pride in ensuring prompt and timely communication with all parties involved, from the couple to the vendors.",
    },
    {
      title: "Experience",
      tagline: "Organized | Personalized | Insightful",
      text: "My job is to make sure your vision of the perfect wedding day is executed exactly the way you planned it, giving you the best experience, a lifetime of memories.",
    },
    {
      title: "Create & Design",
      tagline: "Plan | Inspire | Create",
      text: "From venue to catering, floral to music, I help create and design each individual package to meet your exact needs, partnering up with the best in the wedding industry.",
    },
  ],

  packages: [
    {
      slug: "endearment",
      name: "Endearment",
      icon: "watch",
      pricePrefix: "Starting at",
      price: "$3,000",
      type: "Day-of Coordination",
      flag: "Budget Friendly",
      hours: "Eight hours of day-of service",
      desc: "For couples seeking a dedicated professional to facilitate, execute, and ensure their wedding day unfolds seamlessly.",
      featured: false,
      includes: [
        { title: "One Complimentary Consultation", text: "We'll kick off the planning process with a personalized consultation to understand your vision." },
        { title: "Service Initiation Three Months Before Your Event", text: "Enjoy dedicated assistance in the lead-up to your big day." },
        { title: "Vendor Referrals", text: "Access a curated list of trusted professional vendors that match your style and budget." },
        { title: "Unlimited Email Correspondence", text: "Stay connected with me for any questions or updates as you plan." },
        { title: "Comprehensive Planning Checklist", text: "Receive a detailed checklist to help you stay organized and on track." },
        { title: "Event Timeline Development", text: "I will create a customized timeline to ensure a smooth flow for your wedding day." },
        { title: "Custom Event Layout Creation", text: "Together, we'll design a layout that enhances your venue's atmosphere." },
        { title: "One Site Walkthrough", text: "We'll visit your venue to finalize details and ensure everything is in place." },
        { title: "Thorough Vendor Contract Evaluation", text: "I'll review all vendor contracts to protect your interests." },
        { title: "Pre-Wedding Meetings", text: "We'll meet one month before the wedding and coordinate details two weeks prior." },
        { title: "One-Hour Rehearsal Management", text: "I'll oversee your rehearsal to ensure everyone is prepared and comfortable." },
        { title: "Eight Hours of Day-of Service", text: "Enjoy eight dedicated hours of on-site support on your wedding day (additional hours available if needed)." },
        { title: "On-Site Assistant", text: "An assistant will be present to help manage the day and ensure everything runs smoothly." },
        { title: "Vendor Facilitation and Management", text: "I'll coordinate all vendors on your wedding day for seamless execution." },
      ],
      longDesc: [
        "This service is ideally suited for couples who are seeking a dedicated professional to facilitate, execute, and ensure their wedding day unfolds seamlessly. Planning a wedding can be a complex and emotionally charged process, and while you may have a clear vision and have invested significant time and effort into the details, the presence of an expert can elevate your experience and alleviate stress.",
        "As a wedding professional, my role is to transform your vision into reality while managing the logistical intricacies that can often feel overwhelming. From coordinating with vendors to managing timelines, I will be your trusted partner, ensuring that every element aligns perfectly with your expectations. My goal is to create a fluid experience that allows you to focus on celebrating your love, rather than worrying about the minutiae of the day.",
        "On your wedding day, I will be there to oversee the execution of your carefully crafted plans, addressing any last-minute details that may arise. This includes ensuring that the ceremony starts on time, that the reception flows smoothly, and that all vendors are coordinated effectively. With my experience in event management, I can anticipate potential challenges and navigate them proactively, allowing you and your guests to enjoy the day without interruption.",
        "Furthermore, my comprehensive approach includes a thorough pre-wedding consultation, where we will discuss your preferences and expectations in detail. This process allows me to fully understand your vision, enabling me to tailor my services to meet your unique needs. I will work diligently behind the scenes, ensuring that nothing is overlooked, from the smallest decor detail to the timing of special moments.",
        "Ultimately, this service is designed to provide you with peace of mind, knowing that a professional is managing the intricacies of your wedding day. You deserve to experience every moment of your celebration with joy and confidence, and I am committed to making that a reality. Let's work together to ensure your wedding day is everything you have dreamed of and more.",
      ],
    },
    {
      slug: "adoration",
      name: "Adoration",
      icon: "rings",
      pricePrefix: "Starting at",
      price: "$4,500",
      type: "Partial Planning & Coordination",
      flag: "Most Popular",
      hours: "Ten hours of day-of service",
      desc: "The ideal balance between partial planning and full day coordination — for couples who desire both guidance throughout the planning process and expert management on their wedding day.",
      featured: true,
      includes: [
        { title: "One Complimentary Consultation", text: "We'll start with a personalized consultation to discuss your vision and preferences." },
        { title: "Service Initiation Nine Months Before Your Event", text: "Enjoy dedicated support leading up to your wedding day." },
        { title: "Vendor Referrals", text: "Gain access to a curated list of trusted professional vendors to fit your style and budget." },
        { title: "Unlimited Email Correspondence", text: "Stay connected with me for any questions or updates throughout the planning process." },
        { title: "Comprehensive Planning Checklist", text: "You'll receive a detailed checklist to keep you organized and on track." },
        { title: "Event Timeline Development", text: "I will create a customized timeline to ensure a well-structured flow for your day." },
        { title: "Custom Event Layout Creation", text: "Together, we'll design a layout that maximizes your venue's potential." },
        { title: "Two Site Walkthroughs", text: "We'll visit your venue twice to finalize details and ensure everything is in place." },
        { title: "Thorough Vendor Contract Evaluation", text: "I'll review all vendor contracts to safeguard your interests." },
        { title: "Pre-Wedding Meetings", text: "We'll meet one month before the wedding to finalize plans and two weeks prior for last-minute coordination." },
        { title: "One-Hour Rehearsal Management", text: "I'll oversee your rehearsal to ensure everyone is prepared and comfortable." },
        { title: "Ten Hours of Day-of Service", text: "Enjoy ten dedicated hours of on-site support on your wedding day (additional hours available if needed)." },
        { title: "On-Site Assistant", text: "An assistant will be present to help manage the day and ensure everything runs smoothly." },
        { title: "Vendor Facilitation and Management", text: "I'll direct all vendors on your wedding day, ensuring seamless collaboration." },
      ],
      longDesc: [
        "This hybrid package represents the ideal balance between Partial Planning and Full Day Coordination, making it an exceptional choice for couples who desire both guidance throughout the planning process and expert management on their wedding day. This package is designed to provide unparalleled value, ensuring that every detail is meticulously handled for an unforgettable celebration.",
        "With Amore Coordination, you can expect a planning experience that is not only smooth and efficient but also thoroughly tailored to your unique vision. From the outset, I will work closely with you to understand your preferences, helping to curate a cohesive theme and timeline that reflects your style. My comprehensive planning services include vendor recommendations, budget management, and timeline creation, ensuring no aspect of your wedding is overlooked. This attention to detail means you can relax and enjoy the process, knowing that every component is being managed by seasoned professionals.",
        "On the day of your wedding, my team will be on-site for a full ten hours, offering you peace of mind and allowing you to focus entirely on celebrating your special day. We will take the reins, coordinating seamlessly with all vendors to ensure that the setup, event flow, and breakdown occur flawlessly and according to each venue's specifications. Our proactive approach means we'll address any issues that arise before they impact your experience, ensuring a smooth and stress-free day.",
        "The value of this package lies not only in the hours of coordination provided but also in the expertise and dedication of our team. I understand that your wedding is a once-in-a-lifetime event, and we are committed to making it extraordinary. By choosing this Adoration Package, you're investing in a comprehensive service that combines the best of both worlds, ensuring that your wedding day is executed with precision and creativity.",
        "Ultimately, this package is about delivering an exceptional experience that justifies every penny. You deserve to enjoy your wedding day to the fullest, knowing that every detail has been thoughtfully planned and expertly managed. With Amore Coordination by your side, you can be confident that your wedding will be everything you envisioned and more. Let us bring your dream day to life, allowing you to create lasting memories with your loved ones.",
      ],
    },
    {
      slug: "unforgettable",
      name: "Unforgettable",
      icon: "diamond",
      price: "$6,500",
      type: "Full-Service Planning",
      flag: "Absolute Perfection",
      hours: "Twelve hours of day-of service",
      desc: "A full-service wedding package meticulously crafted for couples who aspire to achieve absolute perfection — comprehensive planning and coordination from start to finish.",
      featured: false,
      includes: [
        { title: "One Free Consultation", text: "We'll begin our journey together with a personalized consultation to understand your vision." },
        { title: "Vendor Recommendations", text: "Benefit from my expertise as I connect you with trusted vendors tailored to your needs." },
        { title: "Four Planning Meetings", text: "Together, we'll meet to discuss every detail, ensuring nothing is overlooked." },
        { title: "Research and Attendance at Three Vendor Meetings", text: "I'll handle vendor interactions, ensuring your preferences are communicated clearly." },
        { title: "Contract Evaluations", text: "I'll meticulously review all vendor contracts to protect your interests." },
        { title: "Detailed Timeline and Layout Construction", text: "You'll receive a well-organized timeline and layout to guide your day." },
        { title: "Vendor Coordination", text: "I'll liaise with all chosen vendors to confirm details and timelines." },
        { title: "Pre-Wedding Meetings", text: "We'll meet one month and two weeks before your wedding to finalize plans and address any last-minute details." },
        { title: "Coordination of Accommodations and Transportation", text: "I'll assist in organizing accommodations, transportation, and childcare needs for your guests." },
        { title: "Etiquette and Protocol Guidance", text: "Get support with traditional wedding etiquette and protocol for a polished event." },
        { title: "Rehearsal Assistance", text: "I'll guide your one-hour rehearsal to ensure everyone is prepared." },
        { title: "Rehearsal Dinner Coordination", text: "I'll help with invites and the overall coordination of your rehearsal dinner." },
        { title: "Transportation of Decor Items", text: "On the day of your wedding, I'll ensure your decor items are transported and set up perfectly." },
        { title: "Twelve Hours of Day-of Coordination Services", text: "Enjoy full support from my team for an entire twelve hours on your wedding day." },
        { title: "Dedicated Assistant", text: "An assistant will be present for the full duration, ensuring all details are managed effectively." },
        { title: "Vendor Communication", text: "I'll maintain communication with all vendors, ensuring a smooth flow of the event." },
        { title: "Decor Setup Oversight", text: "My team will ensure all decor is beautifully arranged according to your vision." },
        { title: "Ceremony Facilitation", text: "I'll facilitate the processional, making sure everything goes according to plan." },
        { title: "Wedding License and Decor Transport", text: "I'll assist with the wedding license and transport any decor items needed for the reception." },
        { title: "Reception Coordination", text: "I'll communicate with the DJ and caterer to ensure a timely start to your reception and dinner service." },
        { title: "Timeline Execution", text: "I'll oversee the execution of the timeline throughout the reception." },
        { title: "Post-Event Breakdown", text: "I'll help with decor breakdown, check out with all vendors, and coordinate with venue staff." },
      ],
      longDesc: [
        "This Full-Service Wedding Package is meticulously crafted for couples who aspire to achieve absolute perfection on their wedding day. This premium offering is an investment in an unforgettable experience, guided by the expertise of a seasoned professional who is dedicated to planning, inspiring, and bringing your unique vision to life.",
        "From the moment you engage with us, you'll experience a transformative approach to wedding planning. We understand that your wedding day is one of the most significant moments in your life, and we are committed to ensuring it reflects your dreams and desires in every detail. With this package, you will benefit from comprehensive planning services that encompass everything from the initial concept to the final execution.",
        "Our collaborative process begins with an in-depth consultation, where we take the time to understand your style, preferences, and aspirations. We will curate a personalized roadmap that guides you through every stage of planning, offering expert advice on vendor selection, budget management, and timeline creation. Our extensive network of trusted vendors means you'll have access to top-tier professionals who share our commitment to excellence, ensuring every aspect of your wedding is handled with care.",
        "On your wedding day, you can rest easy knowing that our team will be with you every step of the way. We will oversee every detail, from setup to breakdown, ensuring that everything unfolds smoothly and according to your vision. With our full attention on the day-of logistics, you and your loved ones can focus on celebrating your love without the burden of coordinating activities. Our meticulous attention to detail ensures that every element — from the floral arrangements to the timing of special moments — is executed flawlessly.",
        "Choosing this Full-Service Wedding Package means investing in a worry-free experience that maximizes the joy and beauty of your special day. You'll benefit from our proactive problem-solving approach, anticipating any potential challenges and addressing them before they become issues. With us by your side, you can embrace the celebration, confident that your day will be nothing short of extraordinary.",
        "This package is not just about planning; it's about creating a once-in-a-lifetime experience that you and your guests will cherish forever. By choosing our Full-Service Wedding Package, you are deciding to elevate your wedding to a level of sophistication and elegance that is truly unmatched. Let us help you craft the wedding of your dreams — an unforgettable celebration that encapsulates your love story in the most beautiful way possible. With Amore Coordination, your vision will become reality, and your wedding day will be a breathtaking reflection of your love.",
      ],
    },
  ],

  // Smaller-celebration packages, provided by Amy (Oct 2026). Rendered as their
  // own section on /services/. Optional fields: pricePrefix, note (overrides
  // packageNote), locations.
  intimate: [
    {
      slug: "micro-wedding",
      name: "Micro Wedding",
      icon: "flutes",
      pricePrefix: "Starting at",
      price: "$3,000",
      type: "Up to 50 Guests",
      hours: "Eight hours of wedding-day coordination",
      desc: "Designed for couples who want an intimate celebration with every detail thoughtfully coordinated.",
      includes: [
        { title: "Complimentary Consultation", text: "We'll discuss your vision and priorities." },
        { title: "Three Months of Planning Support", text: "Dedicated guidance leading up to your wedding day." },
        { title: "Unlimited Email Support", text: "Ongoing assistance throughout the planning process." },
        { title: "Vendor Referrals", text: "Access to trusted professionals suited to your style and budget." },
        { title: "Planning Checklist", text: "A personalized guide to keep you organized and on track." },
        { title: "Customized Wedding-Day Timeline", text: "A detailed timeline coordinating your vendors and key events." },
        { title: "Custom Event Layout", text: "Thoughtful planning for your ceremony, reception, and guest experience." },
        { title: "One Venue Walkthrough", text: "Finalize logistics and details before your wedding day." },
        { title: "Final Vendor Confirmations", text: "I'll confirm final details, arrival times, and logistics with your vendors." },
        { title: "One-Hour Rehearsal Management", text: "I'll guide your rehearsal so everyone feels prepared." },
        { title: "Eight Hours of Wedding-Day Coordination", text: "Dedicated on-site support throughout your celebration." },
        { title: "On-Site Assistant", text: "Additional support to help everything run smoothly." },
        { title: "Ceremony & Reception Management", text: "Coordination of your wedding-day events and transitions." },
        { title: "Vendor Facilitation & Management", text: "I'll oversee your vendors for a seamless celebration." },
      ],
      longDesc: [
        "Designed for couples who want an intimate celebration with every detail thoughtfully coordinated.",
      ],
      note: "Package pricing may vary based on location, guest count, and décor or setup.",
    },
    {
      slug: "pnw-elopement",
      name: "PNW Elopement",
      icon: "mountains",
      price: "$2,500",
      type: "Up to 10 Guests",
      hours: "Up to six hours of on-site coordination",
      desc: "Your day. Your people. Your PNW adventure.",
      includes: [
        { title: "Elopement Planning Consultation", text: "We'll discuss your vision, location, priorities, and plans for the day." },
        { title: "Planning Support", text: "Personalized guidance throughout the planning process." },
        { title: "PNW Location & Vendor Guidance", text: "Recommendations for beautiful locations and trusted local vendors." },
        { title: "Planning Checklist", text: "A simple roadmap to keep everything organized." },
        { title: "Customized Elopement Timeline", text: "A thoughtful timeline designed around your ceremony, photography, travel, and celebration." },
        { title: "Location & Logistics Coordination", text: "Help coordinating timing, transportation, permits, vendors, and other logistical details." },
        { title: "Vendor Coordination", text: "I'll communicate with your participating vendors and confirm final details." },
        { title: "Ceremony Coordination", text: "I'll oversee the flow and logistics of your ceremony." },
        { title: "Personal Details & Décor Setup", text: "Thoughtful placement of designated details, florals, signage, and décor." },
        { title: "Up to 6 Hours of On-Site Coordination", text: "I'll be there to manage the details so you can stay present and enjoy the experience." },
      ],
      longDesc: [
        "Your day. Your people. Your PNW adventure.",
        "For couples dreaming of an intimate Pacific Northwest elopement without having to manage all the details themselves. From mountain views and forest trails to the Oregon Coast and intimate venues, I'll help you create a beautifully organized, stress-free experience.",
      ],
      locations: [
        "Oregon Coast", "Columbia River Gorge", "Mount Hood", "Eastern and NE Oregon",
        "Portland", "Willamette Valley", "Central Oregon", "Washington Coast",
        "Seattle Area", "Olympic Peninsula", "Idaho",
      ],
      note: "Travel fees may apply for locations outside the Portland metro area. Additional hours and services available upon request.",
    },
  ],

  // Applies to every package.
  packageNote:
    "Package price may vary depending on guest count, location, and elaborate décor setup.",

  addons: [
    {
      name: "Rehearsal Dinner Planning",
      tagline: "Planning | Assistance | Execution",
      price: "$400",
      desc: [
        "Planning and assistance with the execution of a rehearsal dinner are crucial for several reasons.",
        "First, it sets the tone for the wedding weekend, providing an opportunity for the couple, family, and close friends to connect in a relaxed environment. A well-organized rehearsal dinner ensures that logistical details, such as the venue, menu, and seating arrangements, are managed effectively, allowing the couple to enjoy the event without stress.",
        "Additionally, having professional assistance ensures that the evening runs smoothly, addressing any last-minute issues that may arise. This preparation fosters a sense of camaraderie among guests, helping to ease any pre-wedding nerves and creating lasting memories before the big day.",
        "Overall, thoughtful planning and execution of the rehearsal dinner contribute to a seamless transition into the wedding festivities.",
      ],
    },
    {
      name: "Additional Support Staff",
      tagline: "Extra assistant staff",
      price: "$40 / hr per assistant",
      desc: [
        "Having an assistant or additional support staff on your wedding day is essential for creating a perfect experience. Their presence allows the couple to focus on enjoying the day rather than managing logistics. Support staff can handle a variety of tasks, such as coordinating with vendors, ensuring the timeline is followed, and addressing any unforeseen issues that arise.",
        "This dedicated assistance helps maintain a calm atmosphere, allowing the couple and their families to savor each moment without stress. Additionally, extra hands can enhance your guests' experience by managing seating, serving, and providing support as needed.",
        "Overall, having a reliable team contributes to a seamless, enjoyable celebration, ensuring your wedding day unfolds exactly as envisioned.",
      ],
    },
    {
      name: "Development & Creation Service",
      tagline: "Timelines | Layouts | Rehearsal Choreographing",
      price: "$400",
      desc: [
        "Timelines, layouts, and rehearsal choreography are essential to a successful wedding. A well-structured timeline ensures that every moment flows smoothly, allowing for a stress-free day.",
        "Detailed layouts facilitate efficient venue setup, ensuring that your guests experience your vision exactly as planned.",
        "Rehearsal choreography allows the bridal party to practice key moments, such as the processional, helping everyone feel confident and prepared.",
        "Together, these elements create a cohesive experience, minimizing potential hiccups and ensuring that your special day unfolds seamlessly, allowing you to focus on what truly matters — celebrating your love with family and friends.",
      ],
    },
    {
      name: "Consultation Services",
      tagline: "Vendor | Venue | Professional Services",
      price: "$300",
      desc: [
        "Having a professional wedding and event coordinator with established connections and relationships in the wedding industry is invaluable for several reasons.",
        "First, their extensive network allows them to recommend trusted vendors who have proven track records, ensuring quality services and products. This not only saves couples time in searching for reliable options but also minimizes the risk of hiring subpar vendors.",
        "Additionally, a planner's knowledge of industry standards and trends enables them to negotiate favorable contracts and secure better pricing, often resulting in cost savings. Their familiarity with vendor personalities and work styles also facilitates smoother communication and collaboration, creating a cohesive team that aligns with the couple's vision. Ultimately, a professional planner's relationships and expertise enhance the overall planning experience, ensuring a seamless, memorable wedding day.",
      ],
    },
  ],
};
